blank_issues_enabled: true
contact_links:
  - name: 💬 Development Process Guide
    url: https://github.com/CoforgeInsurance/Kanban-XP-DevProcess/blob/main/DEVELOPMENT_PROCESS.md
    about: Learn about our Kanban + XP + Lean development process
  - name: 🤖 GitHub Copilot Best Practices
    url: https://docs.github.com/en/copilot
    about: Learn how to work effectively with GitHub Copilot