name: Dependabot Auto-Merge

# Automatically merge safe dependency updates from Dependabot
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge-dependabot:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    # Only run for Dependabot PRs
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Wait for CI checks
        uses: actions/github-script@v7
        id: check-ci
        with:
          script: |
            // Wait up to 3 minutes for CI to complete
            const maxWait = 3 * 60 * 1000;
            const startTime = Date.now();
            
            while (Date.now() - startTime < maxWait) {
              const { data: checks } = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.payload.pull_request.head.sha,
              });
              
              const allChecks = checks.check_runs;
              const completed = allChecks.every(check => check.status === 'completed');
              const allPassed = allChecks.every(check => 
                check.conclusion === 'success' || check.conclusion === 'neutral'
              );
              
              if (completed) {
                return allPassed;
              }
              
              await new Promise(resolve => setTimeout(resolve, 10000));
            }
            
            return false;

      - name: Auto-approve minor/patch updates
        if: |
          steps.check-ci.outputs.result == 'true' &&
          (steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
           steps.metadata.outputs.update-type == 'version-update:semver-minor')
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge minor/patch updates
        if: |
          steps.check-ci.outputs.result == 'true' &&
          (steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
           steps.metadata.outputs.update-type == 'version-update:semver-minor')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '⚠️ **Major Version Update**\n\n' +
                    'This is a major version update from Dependabot.\n\n' +
                    '**Manual review required**:\n' +
                    '- Review breaking changes in changelog\n' +
                    '- Check migration guide\n' +
                    '- Test thoroughly before merging\n' +
                    '- Update code if API changes exist\n\n' +
                    `**Package**: ${context.payload.pull_request.title}\n\n` +
                    '_Major updates are not auto-merged for safety._'
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs-review', 'major-update']
            });
